### ISSUE TITLE
Manuális kód átvizsgálás elvégzése az alkalmazás egy részére + Statikus analízis eszköz futtatása és jelzett hibák átnézése

### ISSUE THREAD

**Issue by rittakos** [BME-MIT-IET/iet-hf2021-ithazi5#2]

**Comment by bidlekm** [comment]
Kérlek ketten dolgozzatok ezen!

**Comment by aprod12** [comment]
Rajta vagyok 👍

**Comment by aprod12** [comment]
Átnéztem a HandlerHelper.cs-t de manuálisan nem találtam semmi hibát. A statikus vizsgálat eredményére és a szerintem javítani szükséges hibákra létrehoztam egy issue-t.

**Comment by rittakos** [comment]
Done
