### ISSUE TITLE
A statikus ellenőrzés eredménye 

### ISSUE THREAD

**Issue by aprod12** [BME-MIT-IET/iet-hf2021-ithazi5#4]
Hibák amiket meg kell néznünk:
	-Replace this type-check-and-cast sequence with an 'as' and a null check. HandlerHelper.cs 317
	-Refactor your code not to use hardcoded absolute paths or URIs.	SparqlServiceDescriber.cs 120	
	-Merge this if statement with the enclosing one. HandlerHelper.cs 431
	-Make '_context' 'readonly'. WebContext.cs	44
	-Use 'string.IsNullOrEmpty()' instead of comparing to empty string. NegotiateByFileExtension.cs

**Comment by rittakos** [comment]
Megnéztem a hibákat, érdemesek a kijavításra.

**Comment by rittakos** [comment]
Úgy itéltem meg, hogy a második hiba nem hiba, hanem szándékosan van így, ezért kiiktattam a warningot

**Comment by rittakos** [comment]
Done
