### ISSUE TITLE
Nem-funkcionális jellemzők vizsgálata (teljesítmény, stresszteszt, biztonság, használhatóság...)

### ISSUE THREAD

**Issue by bidlekm** [BME-MIT-IET/iet-hf2021-ithazi5#5]
Termék/felhasználó fókusz egyik részfeladata, meg kell csinálni hogy meglegyen a kettes

**Comment by Geovanny27** [comment]
Csináltam rá branchet, azon dolgozzunk

**Comment by Geovanny27** [comment]
Teszteljünk ezen szempontok alapján:

- [x] teljesítmény

- [x] stresszteszt

- [x] használhatóság

**Comment by Geovanny27** [comment]
Elkezdem a teljesítmény tesztelését

**Comment by Geovanny27** [comment]
Teljesítmény tesztelés eredménye: 
1 tripla létrehozása: 124ms
2 tripla létrehozása: 167ms
10 tripla létrehozása: 112ms
100 tripla létrehozása: 104ms
1000 tripla létrehozása: 132ms
10000 tripla létrehozása: 332ms
100000 tripla létrehozása: 3447ms

szepmuveszeti.n3 betöltése: 25045ms

Triplák létrehozásánál észrevételem szerint 1000-ig nem is látszik teljesítménybeli különbség, azután viszont jelentősen változik, főleg már 10-100 ezres nagyságrendeknél.

**Comment by Geovanny27** [comment]
Elkezdem a használhatóság tesztelését

**Comment by Geovanny27** [comment]
Használhatóság tesztelésének céljai:
- RDF kiírása n3 file-ba
- Egy sikeres SPARQL lekérdezés megírása

**Comment by Geovanny27** [comment]
Használhatóság tesztelés eredménye:
- RDF kiírása n3 file-ba:
Sikerült, az API dokumentációja korrekt, nem volt sok probléma ennek megvalósításával.
- Egy sikeres SPARQL lekérdezés megírása:
Nem sikerült, hiába a sok szenvedés, nem működik a dokumentációban található példakód sem. @bidlekm átveszi a stafétát, ő is megpróbálkozik vele. 
Update#1: @aprod12 is próbálkozik.
Update#2: @bidlekm sikerrel járt.
